create table if not exists public.callbacks (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  issue text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  user_email text,
  issue text not null,
  chat_history text not null,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

alter table public.callbacks enable row level security;
alter table public.tickets enable row level security;

-- Basic policies for authenticated and anonymous inserts from the app.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'callbacks' and policyname = 'callbacks_insert'
  ) then
    create policy "callbacks_insert" on public.callbacks
    for insert
    with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'tickets' and policyname = 'tickets_insert'
  ) then
    create policy "tickets_insert" on public.tickets
    for insert
    with check (true);
  end if;
end
$$;
